-- Run after Movie.txt (database system_rekomendacji must exist with Filmy populated).
USE system_rekomendacji;

CREATE TABLE IF NOT EXISTS GdzieObejrzec (
    id_opcji INT PRIMARY KEY AUTO_INCREMENT,
    id_filmu INT NOT NULL,
    provider VARCHAR(128) NOT NULL,
    url VARCHAR(1024) NOT NULL,
    FOREIGN KEY (id_filmu) REFERENCES Filmy(id_filmu)
);

-- Demo deep links: JustWatch search + Amazon search (availability varies by region).
INSERT INTO GdzieObejrzec (id_filmu, provider, url) VALUES
(1, 'JustWatch', 'https://www.justwatch.com/us/search?q=The+Shawshank+Redemption'),
(1, 'Prime Video', 'https://www.amazon.com/s?k=The+Shawshank+Redemption'),
(1, 'Netflix', 'https://www.netflix.com/search?q=The%20Shawshank%20Redemption'),
(2, 'JustWatch', 'https://www.justwatch.com/us/search?q=The+Godfather'),
(2, 'Prime Video', 'https://www.amazon.com/s?k=The+Godfather'),
(2, 'Apple TV', 'https://tv.apple.com/search?term=The%20Godfather'),
(3, 'JustWatch', 'https://www.justwatch.com/us/search?q=The+Dark+Knight'),
(3, 'Prime Video', 'https://www.amazon.com/s?k=The+Dark+Knight'),
(3, 'Max', 'https://www.max.com/search?q=The%20Dark%20Knight'),
(4, 'JustWatch', 'https://www.justwatch.com/us/search?q=Pulp+Fiction'),
(4, 'Prime Video', 'https://www.amazon.com/s?k=Pulp+Fiction'),
(4, 'Netflix', 'https://www.netflix.com/search?q=Pulp%20Fiction'),
(5, 'JustWatch', 'https://www.justwatch.com/us/search?q=Schindlers+List'),
(5, 'Prime Video', 'https://www.amazon.com/s?k=Schindler%27s+List'),
(5, 'Apple TV', 'https://tv.apple.com/search?term=Schindler%27s%20List'),
(6, 'JustWatch', 'https://www.justwatch.com/us/search?q=Lord+of+the+Rings+Return+of+the+King'),
(6, 'Prime Video', 'https://www.amazon.com/s?k=The+Lord+of+the+Rings+The+Return+of+the+King'),
(6, 'Max', 'https://www.max.com/search?q=Return%20of%20the%20King'),
(7, 'JustWatch', 'https://www.justwatch.com/us/search?q=Inception'),
(7, 'Prime Video', 'https://www.amazon.com/s?k=Inception'),
(7, 'Netflix', 'https://www.netflix.com/search?q=Inception'),
(8, 'JustWatch', 'https://www.justwatch.com/us/search?q=Fight+Club'),
(8, 'Prime Video', 'https://www.amazon.com/s?k=Fight+Club'),
(8, 'Apple TV', 'https://tv.apple.com/search?term=Fight%20Club'),
(9, 'JustWatch', 'https://www.justwatch.com/us/search?q=The+Matrix'),
(9, 'Prime Video', 'https://www.amazon.com/s?k=The+Matrix'),
(9, 'Netflix', 'https://www.netflix.com/search?q=The%20Matrix'),
(10, 'JustWatch', 'https://www.justwatch.com/us/search?q=Forrest+Gump'),
(10, 'Prime Video', 'https://www.amazon.com/s?k=Forrest+Gump'),
(10, 'Netflix', 'https://www.netflix.com/search?q=Forrest%20Gump'),
(11, 'JustWatch', 'https://www.justwatch.com/us/search?q=Star+Wars+A+New+Hope'),
(11, 'Prime Video', 'https://www.amazon.com/s?k=Star+Wars+A+New+Hope'),
(11, 'Disney+', 'https://www.disneyplus.com/search?q=Star%20Wars'),
(12, 'JustWatch', 'https://www.justwatch.com/us/search?q=Silence+of+the+Lambs'),
(12, 'Prime Video', 'https://www.amazon.com/s?k=The+Silence+of+the+Lambs'),
(12, 'Netflix', 'https://www.netflix.com/search?q=Silence%20of%20the%20Lambs'),
(13, 'JustWatch', 'https://www.justwatch.com/us/search?q=Se7en'),
(13, 'Prime Video', 'https://www.amazon.com/s?k=Se7en'),
(13, 'Max', 'https://www.max.com/search?q=Se7en'),
(14, 'JustWatch', 'https://www.justwatch.com/us/search?q=Interstellar'),
(14, 'Prime Video', 'https://www.amazon.com/s?k=Interstellar'),
(14, 'Paramount+', 'https://www.paramountplus.com/search/?q=Interstellar'),
(15, 'JustWatch', 'https://www.justwatch.com/us/search?q=The+Green+Mile'),
(15, 'Prime Video', 'https://www.amazon.com/s?k=The+Green+Mile'),
(15, 'Netflix', 'https://www.netflix.com/search?q=The%20Green%20Mile'),
(16, 'JustWatch', 'https://www.justwatch.com/us/search?q=Gladiator'),
(16, 'Prime Video', 'https://www.amazon.com/s?k=Gladiator'),
(16, 'Netflix', 'https://www.netflix.com/search?q=Gladiator'),
(17, 'JustWatch', 'https://www.justwatch.com/us/search?q=The+Departed'),
(17, 'Prime Video', 'https://www.amazon.com/s?k=The+Departed'),
(17, 'Max', 'https://www.max.com/search?q=The%20Departed'),
(18, 'JustWatch', 'https://www.justwatch.com/us/search?q=The+Prestige'),
(18, 'Prime Video', 'https://www.amazon.com/s?k=The+Prestige'),
(18, 'Netflix', 'https://www.netflix.com/search?q=The%20Prestige'),
(19, 'JustWatch', 'https://www.justwatch.com/us/search?q=Django+Unchained'),
(19, 'Prime Video', 'https://www.amazon.com/s?k=Django+Unchained'),
(19, 'Netflix', 'https://www.netflix.com/search?q=Django%20Unchained'),
(20, 'JustWatch', 'https://www.justwatch.com/us/search?q=Whiplash'),
(20, 'Prime Video', 'https://www.amazon.com/s?k=Whiplash'),
(20, 'Apple TV', 'https://tv.apple.com/search?term=Whiplash');
